spring.application.name=chess.vikas
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/chessdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:vikas}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

