spring.application.name=chess.vikas
spring.datasource.url=jdbc:postgresql://localhost:5433/chessdb
spring.datasource.username=postgres
spring.datasource.password=vikas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

